name: hallu
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pip:
    - chardet
    - charset-normalizer>=3.1.0
    - scikit-learn
    - pandas
    - jupyterlab
    - notebook
    - matplotlib
    - seaborn
    - ipywidgets
    - scipy
    - wandb
    - openai
    - tiktoken
    - nltk
    - tenacity
    - tokenizers>=0.13.3
    - accelerate
    - ml_collections
    - torchmetrics
    - einops
    - bitsandbytes
    - sentencepiece
    - transformers>=4.51.0
    - hf_xet